// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAScKj1WM1zAlxsEMPXFsAz4_LRtZ-O-Ws',
    appId: '1:690954328849:web:76947e81c8816fd8830ab0',
    messagingSenderId: '690954328849',
    projectId: 'oquway',
    authDomain: 'oquway.firebaseapp.com',
    storageBucket: 'oquway.appspot.com',
    measurementId: 'G-X73R3CF8BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMCIqf176_5HfrnKjVWSCQnPYGsn6PoNM',
    appId: '1:690954328849:android:241b0221b0ff978d830ab0',
    messagingSenderId: '690954328849',
    projectId: 'oquway',
    storageBucket: 'oquway.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC82ejtwURJECL0-oolwT4MGF0myAfYOJc',
    appId: '1:690954328849:ios:6bbe41b65f07ad24830ab0',
    messagingSenderId: '690954328849',
    projectId: 'oquway',
    storageBucket: 'oquway.appspot.com',
    iosClientId: '690954328849-ppf1b5ipillvpfo7kqedgvgliqsvbj9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.oquWay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC82ejtwURJECL0-oolwT4MGF0myAfYOJc',
    appId: '1:690954328849:ios:6bbe41b65f07ad24830ab0',
    messagingSenderId: '690954328849',
    projectId: 'oquway',
    storageBucket: 'oquway.appspot.com',
    iosClientId: '690954328849-ppf1b5ipillvpfo7kqedgvgliqsvbj9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.oquWay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAScKj1WM1zAlxsEMPXFsAz4_LRtZ-O-Ws',
    appId: '1:690954328849:web:9b98d90b4e40cbfb830ab0',
    messagingSenderId: '690954328849',
    projectId: 'oquway',
    authDomain: 'oquway.firebaseapp.com',
    storageBucket: 'oquway.appspot.com',
    measurementId: 'G-V9L82ZSGMQ',
  );
}
